[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "pacman"
version = "0.1.0"
description = "Pacman built with Mini Arcade."
requires-python = ">=3.9,<3.12"
dependencies = [
  "mini-arcade-core~=1.5",
  "mini-arcade~=1.5",
  "mini-arcade-pygame-backend~=1.5",
  "mini-arcade-native-backend~=1.5",
]

[tool.poetry]
packages = [{ include = "pacman", from = "src" }]

[project.scripts]
pacman = "pacman.app:run"

[tool.mini-arcade.game]
id = "pacman"
entrypoint = "manage.py"
source_roots = ["src"]
