name: Release Major/Minor

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: "Version bump type"
        required: true
        type: choice
        options:
          - minor
          - major

permissions:
  contents: write

jobs:
  release:
    uses: trivox-io/mini-arcade/.github/workflows/reusable-release-package.yml@main
    with:
      project_name: mini-arcade-pygame-backend
      working_directory: .
      version_file: pyproject.toml
      bump_type: ${{ inputs.bump_type }}
      merge_develop_into_main: true
      sync_develop_from_main: true
      tag_prefix: mini-arcade-pygame-backend
    secrets:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
