name: Sync Develop From Main

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    uses: trivox-io/mini-arcade/.github/workflows/reusable-sync-develop.yml@main
    with:
      stable_branch: main
      develop_branch: develop
