name: CI

on:
  push:
    branches:
      - main
      - develop
      - "feature/**"
      - "hotfix/**"
  pull_request:
    branches:
      - main
      - develop

jobs:
  python-ci:
    uses: trivox-io/mini-arcade/.github/workflows/reusable-python-ci.yml@main
    with:
      project_name: mini-arcade-core
      lint_path: src/mini_arcade_core
      working_directory: .
